# Generated by Django 4.0.5 on 2022-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadratic_equation', '0002_equations_d_equations_x1_equations_x2'),
    ]

    operations = [
        migrations.AddField(
            model_name='equations',
            name='b',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='equations',
            name='c',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
