# Generated by Django 4.0.5 on 2022-06-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuftBallons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(choices=[(0, 'синий'), (1, 'зеленый'), (2, 'красный')])),
            ],
            options={
                'verbose_name': 'LuftBallon',
                'verbose_name_plural': 'LuftBallons',
            },
        ),
    ]
